---
title: "Homework 6"
author: "Lily Wang"
date: "11/24/2020"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

## Problem 1

```{r}
hom_df <- read_csv("./data/homicide-data.csv") %>% 
   mutate(
    victim_age = as.numeric(victim_age),
    city_state = str_c(city, state, sep = "_"),
    resolved = case_when(
      disposition == "Closed without arrest" ~ 0,
      disposition == "Closed by arrest" ~ 1,
      disposition == "Open/No arrest" ~ 0)
    ) %>% 
  select(city_state, victim_age, victim_race, victim_sex, resolved) %>% 
  filter(city_state != "Tulsa_AL",
         victim_race %in% c("White", "Black"))
  
```

Start with one city: 

```{r}
baltimore_df <- hom_df %>% 
  filter(city_state == "Baltimore_MD")

glm(resolved ~ victim_age + victim_race + victim_sex, data = baltimore_df, family = binomial()) %>% 
  broom::tidy() %>% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) %>% 
  select(term, OR, starts_with("CI")) %>% 
  knitr::kable(digits = 3)
```

Repeat across all cities:

```{r}
model_results_df <- hom_df %>% 
  nest(data = -city_state) %>% 
  mutate(
    models = map(.x = data, ~glm(resolved ~ victim_age + victim_race + victim_sex, data = .x, family = binomial())),
    results = map(models, broom::tidy)
  ) %>% 
  select(city_state, results) %>% 
  unnest(results) %>% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) %>% 
  select(city_state, term, OR, starts_with("CI"))
```

Plot OR by sex:

```{r}
model_results_df %>% 
  filter(term == "victim_sexMale") %>% 
  mutate(city_state = fct_reorder(city_state, OR)) %>% 
  ggplot(aes(x = city_state, y = OR)) + 
  geom_point() +
  geom_errorbar(aes(ymin = CI_lower, ymax = CI_upper)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

It seems that in a majority of the cities, the odds of a male victim case being resolved is lower than if the victim was female.


## Problem 2

```{r}
weight_df <- read_csv("./data/birthweight.csv")

lm(bwt ~ gaweeks, data = weight_df)

  
```


## Problem 3

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

